// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// big_pls_fit_cpp
SEXP big_pls_fit_cpp(SEXP x_ptr, NumericVector y, int ncomp, bool center_x, bool scale_x, bool center_y, bool scale_y);
RcppExport SEXP _bigPLSR_big_pls_fit_cpp(SEXP x_ptrSEXP, SEXP ySEXP, SEXP ncompSEXP, SEXP center_xSEXP, SEXP scale_xSEXP, SEXP center_ySEXP, SEXP scale_ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x_ptr(x_ptrSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type ncomp(ncompSEXP);
    Rcpp::traits::input_parameter< bool >::type center_x(center_xSEXP);
    Rcpp::traits::input_parameter< bool >::type scale_x(scale_xSEXP);
    Rcpp::traits::input_parameter< bool >::type center_y(center_ySEXP);
    Rcpp::traits::input_parameter< bool >::type scale_y(scale_ySEXP);
    rcpp_result_gen = Rcpp::wrap(big_pls_fit_cpp(x_ptr, y, ncomp, center_x, scale_x, center_y, scale_y));
    return rcpp_result_gen;
END_RCPP
}
// big_pls_stream_cpp
SEXP big_pls_stream_cpp(SEXP x_ptr, NumericVector y, int ncomp, bool center_x, bool scale_x, bool center_y, bool scale_y, int chunk_size);
RcppExport SEXP _bigPLSR_big_pls_stream_cpp(SEXP x_ptrSEXP, SEXP ySEXP, SEXP ncompSEXP, SEXP center_xSEXP, SEXP scale_xSEXP, SEXP center_ySEXP, SEXP scale_ySEXP, SEXP chunk_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x_ptr(x_ptrSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type ncomp(ncompSEXP);
    Rcpp::traits::input_parameter< bool >::type center_x(center_xSEXP);
    Rcpp::traits::input_parameter< bool >::type scale_x(scale_xSEXP);
    Rcpp::traits::input_parameter< bool >::type center_y(center_ySEXP);
    Rcpp::traits::input_parameter< bool >::type scale_y(scale_ySEXP);
    Rcpp::traits::input_parameter< int >::type chunk_size(chunk_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(big_pls_stream_cpp(x_ptr, y, ncomp, center_x, scale_x, center_y, scale_y, chunk_size));
    return rcpp_result_gen;
END_RCPP
}
// cpp_big_pls_fit
SEXP cpp_big_pls_fit(SEXP x_ptr, SEXP y_ptr, int ncomp, double tol);
RcppExport SEXP _bigPLSR_cpp_big_pls_fit(SEXP x_ptrSEXP, SEXP y_ptrSEXP, SEXP ncompSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x_ptr(x_ptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y_ptr(y_ptrSEXP);
    Rcpp::traits::input_parameter< int >::type ncomp(ncompSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_big_pls_fit(x_ptr, y_ptr, ncomp, tol));
    return rcpp_result_gen;
END_RCPP
}
// cpp_big_pls_stream_fit
SEXP cpp_big_pls_stream_fit(SEXP x_ptr, SEXP y_ptr, int ncomp, std::size_t chunk_size, double tol);
RcppExport SEXP _bigPLSR_cpp_big_pls_stream_fit(SEXP x_ptrSEXP, SEXP y_ptrSEXP, SEXP ncompSEXP, SEXP chunk_sizeSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x_ptr(x_ptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y_ptr(y_ptrSEXP);
    Rcpp::traits::input_parameter< int >::type ncomp(ncompSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type chunk_size(chunk_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_big_pls_stream_fit(x_ptr, y_ptr, ncomp, chunk_size, tol));
    return rcpp_result_gen;
END_RCPP
}
// pls_nipals_bigmemory
List pls_nipals_bigmemory(SEXP X_ptrSEXP, SEXP y_ptrSEXP, int ncomp, bool center, bool scale, double tol, int max_iter);
RcppExport SEXP _bigPLSR_pls_nipals_bigmemory(SEXP X_ptrSEXPSEXP, SEXP y_ptrSEXPSEXP, SEXP ncompSEXP, SEXP centerSEXP, SEXP scaleSEXP, SEXP tolSEXP, SEXP max_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type X_ptrSEXP(X_ptrSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y_ptrSEXP(y_ptrSEXPSEXP);
    Rcpp::traits::input_parameter< int >::type ncomp(ncompSEXP);
    Rcpp::traits::input_parameter< bool >::type center(centerSEXP);
    Rcpp::traits::input_parameter< bool >::type scale(scaleSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(pls_nipals_bigmemory(X_ptrSEXP, y_ptrSEXP, ncomp, center, scale, tol, max_iter));
    return rcpp_result_gen;
END_RCPP
}
// pls_streaming_bigmemory
List pls_streaming_bigmemory(SEXP X_ptrSEXP, SEXP y_ptrSEXP, int ncomp, int block_size, bool center, bool scale, double tol);
RcppExport SEXP _bigPLSR_pls_streaming_bigmemory(SEXP X_ptrSEXPSEXP, SEXP y_ptrSEXPSEXP, SEXP ncompSEXP, SEXP block_sizeSEXP, SEXP centerSEXP, SEXP scaleSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type X_ptrSEXP(X_ptrSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y_ptrSEXP(y_ptrSEXPSEXP);
    Rcpp::traits::input_parameter< int >::type ncomp(ncompSEXP);
    Rcpp::traits::input_parameter< int >::type block_size(block_sizeSEXP);
    Rcpp::traits::input_parameter< bool >::type center(centerSEXP);
    Rcpp::traits::input_parameter< bool >::type scale(scaleSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(pls_streaming_bigmemory(X_ptrSEXP, y_ptrSEXP, ncomp, block_size, center, scale, tol));
    return rcpp_result_gen;
END_RCPP
}
// big_plsr_fit_nipals
Rcpp::List big_plsr_fit_nipals(SEXP X_ptr, SEXP Y_ptr, int ncomp, bool center, bool scale);
RcppExport SEXP _bigPLSR_big_plsr_fit_nipals(SEXP X_ptrSEXP, SEXP Y_ptrSEXP, SEXP ncompSEXP, SEXP centerSEXP, SEXP scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type X_ptr(X_ptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Y_ptr(Y_ptrSEXP);
    Rcpp::traits::input_parameter< int >::type ncomp(ncompSEXP);
    Rcpp::traits::input_parameter< bool >::type center(centerSEXP);
    Rcpp::traits::input_parameter< bool >::type scale(scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(big_plsr_fit_nipals(X_ptr, Y_ptr, ncomp, center, scale));
    return rcpp_result_gen;
END_RCPP
}
// big_plsr_fit
Rcpp::List big_plsr_fit(SEXP X_ptr, SEXP Y_ptr, int ncomp, bool center, bool scale);
RcppExport SEXP _bigPLSR_big_plsr_fit(SEXP X_ptrSEXP, SEXP Y_ptrSEXP, SEXP ncompSEXP, SEXP centerSEXP, SEXP scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type X_ptr(X_ptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Y_ptr(Y_ptrSEXP);
    Rcpp::traits::input_parameter< int >::type ncomp(ncompSEXP);
    Rcpp::traits::input_parameter< bool >::type center(centerSEXP);
    Rcpp::traits::input_parameter< bool >::type scale(scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(big_plsr_fit(X_ptr, Y_ptr, ncomp, center, scale));
    return rcpp_result_gen;
END_RCPP
}
// big_plsr_stream_fit
Rcpp::List big_plsr_stream_fit(SEXP X_ptr, SEXP Y_ptr, int ncomp, bool center, bool scale, std::size_t block_size);
RcppExport SEXP _bigPLSR_big_plsr_stream_fit(SEXP X_ptrSEXP, SEXP Y_ptrSEXP, SEXP ncompSEXP, SEXP centerSEXP, SEXP scaleSEXP, SEXP block_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type X_ptr(X_ptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Y_ptr(Y_ptrSEXP);
    Rcpp::traits::input_parameter< int >::type ncomp(ncompSEXP);
    Rcpp::traits::input_parameter< bool >::type center(centerSEXP);
    Rcpp::traits::input_parameter< bool >::type scale(scaleSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type block_size(block_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(big_plsr_stream_fit(X_ptr, Y_ptr, ncomp, center, scale, block_size));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_bigPLSR_big_pls_fit_cpp", (DL_FUNC) &_bigPLSR_big_pls_fit_cpp, 7},
    {"_bigPLSR_big_pls_stream_cpp", (DL_FUNC) &_bigPLSR_big_pls_stream_cpp, 8},
    {"_bigPLSR_cpp_big_pls_fit", (DL_FUNC) &_bigPLSR_cpp_big_pls_fit, 4},
    {"_bigPLSR_cpp_big_pls_stream_fit", (DL_FUNC) &_bigPLSR_cpp_big_pls_stream_fit, 5},
    {"_bigPLSR_pls_nipals_bigmemory", (DL_FUNC) &_bigPLSR_pls_nipals_bigmemory, 7},
    {"_bigPLSR_pls_streaming_bigmemory", (DL_FUNC) &_bigPLSR_pls_streaming_bigmemory, 7},
    {"_bigPLSR_big_plsr_fit_nipals", (DL_FUNC) &_bigPLSR_big_plsr_fit_nipals, 5},
    {"_bigPLSR_big_plsr_fit", (DL_FUNC) &_bigPLSR_big_plsr_fit, 5},
    {"_bigPLSR_big_plsr_stream_fit", (DL_FUNC) &_bigPLSR_big_plsr_stream_fit, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_bigPLSR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
