# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

big_pls_fit_cpp <- function(x_ptr, y, ncomp, center_x, scale_x, center_y, scale_y, return_big) {
    .Call(`_bigPLSR_big_pls_fit_cpp`, x_ptr, y, ncomp, center_x, scale_x, center_y, scale_y, return_big)
}

big_pls_stream_cpp <- function(x_ptr, y, ncomp, center_x, scale_x, center_y, scale_y, chunk_size, return_big) {
    .Call(`_bigPLSR_big_pls_stream_cpp`, x_ptr, y, ncomp, center_x, scale_x, center_y, scale_y, chunk_size, return_big)
}

cpp_dense_pls_fit <- function(X, y, ncomp, tol, compute_scores = FALSE, scores_big = FALSE, scores_name = "scores") {
    .Call(`_bigPLSR_cpp_dense_pls_fit`, X, y, ncomp, tol, compute_scores, scores_big, scores_name)
}

cpp_big_pls_fit <- function(x_ptr, y_ptr, ncomp, tol, return_big) {
    .Call(`_bigPLSR_cpp_big_pls_fit`, x_ptr, y_ptr, ncomp, tol, return_big)
}

cpp_big_pls_stream_fit <- function(x_ptr, y_ptr, ncomp, chunk_size, tol, return_big) {
    .Call(`_bigPLSR_cpp_big_pls_stream_fit`, x_ptr, y_ptr, ncomp, chunk_size, tol, return_big)
}

pls_nipals_bigmemory <- function(X_ptrSEXP, y_ptrSEXP, ncomp, center, scale, tol, max_iter, return_big) {
    .Call(`_bigPLSR_pls_nipals_bigmemory`, X_ptrSEXP, y_ptrSEXP, ncomp, center, scale, tol, max_iter, return_big)
}

pls_streaming_bigmemory <- function(X_ptrSEXP, y_ptrSEXP, ncomp, chunk_size, center, scale, tol, return_big) {
    .Call(`_bigPLSR_pls_streaming_bigmemory`, X_ptrSEXP, y_ptrSEXP, ncomp, chunk_size, center, scale, tol, return_big)
}

big_plsr_fit_nipals <- function(X_ptr, Y_ptr, ncomp, center = TRUE, scale = FALSE, return_big = FALSE) {
    .Call(`_bigPLSR_big_plsr_fit_nipals`, X_ptr, Y_ptr, ncomp, center, scale, return_big)
}

big_plsr_stream_fit_nipals <- function(X_ptr, Y_ptr, ncomp, center = TRUE, scale = FALSE, chunk_size = 1024L, return_big = FALSE) {
    .Call(`_bigPLSR_big_plsr_stream_fit_nipals`, X_ptr, Y_ptr, ncomp, center, scale, chunk_size, return_big)
}

big_plsr_fit <- function(X_ptr, Y_ptr, ncomp, center = TRUE, scale = FALSE, return_big = FALSE) {
    .Call(`_bigPLSR_big_plsr_fit`, X_ptr, Y_ptr, ncomp, center, scale, return_big)
}

big_plsr_stream_fit <- function(X_ptr, Y_ptr, ncomp, center = TRUE, scale = FALSE, chunk_size = 1024L, return_big = FALSE) {
    .Call(`_bigPLSR_big_plsr_stream_fit`, X_ptr, Y_ptr, ncomp, center, scale, chunk_size, return_big)
}

