# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

big_pls_fit_cpp <- function(x_ptr, y, ncomp, center_x, scale_x, center_y, scale_y, return_big) {
    .Call(`_bigPLSR_big_pls_fit_cpp`, x_ptr, y, ncomp, center_x, scale_x, center_y, scale_y, return_big)
}

big_pls_stream_cpp <- function(x_ptr, y, ncomp, center_x, scale_x, center_y, scale_y, chunk_size, return_big) {
    .Call(`_bigPLSR_big_pls_stream_cpp`, x_ptr, y, ncomp, center_x, scale_x, center_y, scale_y, chunk_size, return_big)
}

cpp_dense_pls_fit <- function(X, y, ncomp, tol, compute_scores = FALSE, scores_big = FALSE, scores_name = "scores") {
    .Call(`_bigPLSR_cpp_dense_pls_fit`, X, y, ncomp, tol, compute_scores, scores_big, scores_name)
}

#' Internal kernel and wide-kernel PLS solver
#'
#' @param X Centered design matrix.
#' @param Y Centered response matrix.
#' @param ncomp Maximum number of components.
#' @param tol Numerical tolerance.
#' @param wide Whether to use the wide-kernel update.
#' @return A list containing the kernel PLS factors.
#'
cpp_kernel_pls <- function(X, Y, ncomp, tol, wide) {
    .Call(`_bigPLSR_cpp_kernel_pls`, X, Y, ncomp, tol, wide)
}

cpp_big_pls_fit <- function(x_ptr, y_ptr, ncomp, tol, return_big) {
    .Call(`_bigPLSR_cpp_big_pls_fit`, x_ptr, y_ptr, ncomp, tol, return_big)
}

cpp_big_pls_stream_fit <- function(x_ptr, y_ptr, ncomp, chunk_size, tol, return_big) {
    .Call(`_bigPLSR_cpp_big_pls_stream_fit`, x_ptr, y_ptr, ncomp, chunk_size, tol, return_big)
}

cpp_bigmem_cross <- function(X_ptrSEXP, Y_ptrSEXP, chunk_size) {
    .Call(`_bigPLSR_cpp_bigmem_cross`, X_ptrSEXP, Y_ptrSEXP, chunk_size)
}

cpp_simpls_from_cross <- function(XtX, XtY, x_mean, y_mean, ncomp, tol) {
    .Call(`_bigPLSR_cpp_simpls_from_cross`, XtX, XtY, x_mean, y_mean, ncomp, tol)
}

cpp_stream_scores_given_W <- function(X_ptrSEXP, W, x_mean, chunk_size, scores_sinkSEXP, return_big) {
    .Call(`_bigPLSR_cpp_stream_scores_given_W`, X_ptrSEXP, W, x_mean, chunk_size, scores_sinkSEXP, return_big)
}

pls_nipals_bigmemory <- function(X_ptrSEXP, y_ptrSEXP, ncomp, center, scale, tol, max_iter, return_big) {
    .Call(`_bigPLSR_pls_nipals_bigmemory`, X_ptrSEXP, y_ptrSEXP, ncomp, center, scale, tol, max_iter, return_big)
}

pls_streaming_bigmemory <- function(X_ptrSEXP, y_ptrSEXP, ncomp, chunk_size, center, scale, tol, return_big) {
    .Call(`_bigPLSR_pls_streaming_bigmemory`, X_ptrSEXP, y_ptrSEXP, ncomp, chunk_size, center, scale, tol, return_big)
}

cpp_big_pls_stream_fit_sink <- function(X_ptrSEXP, y_ptrSEXP, scores_sinkSEXP, ncomp, chunk_size, tol, return_big) {
    .Call(`_bigPLSR_cpp_big_pls_stream_fit_sink`, X_ptrSEXP, y_ptrSEXP, scores_sinkSEXP, ncomp, chunk_size, tol, return_big)
}

cpp_dense_plsr_nipals <- function(X, Y, ncomp, tol, compute_scores = FALSE, scores_big = FALSE, scores_name = "scores") {
    .Call(`_bigPLSR_cpp_dense_plsr_nipals`, X, Y, ncomp, tol, compute_scores, scores_big, scores_name)
}

big_plsr_fit_nipals <- function(X_ptr, Y_ptr, ncomp, center = TRUE, scale = FALSE, return_big = FALSE) {
    .Call(`_bigPLSR_big_plsr_fit_nipals`, X_ptr, Y_ptr, ncomp, center, scale, return_big)
}

big_plsr_stream_fit_nipals <- function(X_ptr, Y_ptr, ncomp, center = TRUE, scale = FALSE, chunk_size = 1024L, return_big = FALSE) {
    .Call(`_bigPLSR_big_plsr_stream_fit_nipals`, X_ptr, Y_ptr, ncomp, center, scale, chunk_size, return_big)
}

big_plsr_fit <- function(X_ptr, Y_ptr, ncomp, center = TRUE, scale = FALSE, return_big = FALSE) {
    .Call(`_bigPLSR_big_plsr_fit`, X_ptr, Y_ptr, ncomp, center, scale, return_big)
}

big_plsr_stream_fit <- function(X_ptr, Y_ptr, ncomp, center = TRUE, scale = FALSE, chunk_size = 1024L, return_big = FALSE) {
    .Call(`_bigPLSR_big_plsr_stream_fit`, X_ptr, Y_ptr, ncomp, center, scale, chunk_size, return_big)
}

